FROM node:20.16.0-alpine

RUN apk add --no-cache bash
RUN npm i -g @nestjs/cli typescript ts-node

COPY package*.json /tmp/app/
RUN cd /tmp/app && npm install

COPY . /usr/src/app
RUN cp -a /tmp/app/node_modules /usr/src/app
COPY ./wait-for-it.sh /opt/wait-for-it.sh
RUN chmod +x /opt/wait-for-it.sh
# COPY ./startup.relational.dev.sh /opt/startup.relational.dev.sh

# ENVS
ARG NODE_ENV
ARG APP_PORT
ARG APP_NAME
ARG API_PREFIX
ARG APP_FALLBACK_LANGUAGE
ARG APP_HEADER_LANGUAGE
ARG FRONTEND_DOMAIN
ARG BACKEND_DOMAIN
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_NAME
ARG REDIS_HOST
ARG REDIS_PORT
ARG MINIO_ROOT_USER
ARG MINIO_ROOT_PASSWORD
ARG FILE_DRIVER
ARG ACCESS_KEY_ID
ARG SECRET_ACCESS_KEY
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG MAIL_IGNORE_TLS
ARG MAIL_SECURE
ARG MAIL_REQUIRE_TLS
ARG MAIL_DEFAULT_EMAIL
ARG MAIL_DEFAULT_NAME
ARG MAIL_CLIENT_PORT
ARG AUTH_JWT_SECRET
ARG AUTH_JWT_TOKEN_EXPIRES_IN
ARG AUTH_REFRESH_SECRET
ARG AUTH_REFRESH_TOKEN_EXPIRES_IN
ARG AUTH_FORGOT_SECRET
ARG AUTH_FORGOT_TOKEN_EXPIRES_IN
ARG AUTH_CONFIRM_EMAIL_SECRET
ARG AUTH_CONFIRM_EMAIL_TOKEN_EXPIRES_IN

ENV NODE_ENV=$NODE_ENV
ENV APP_PORT=$APP_PORT
ENV APP_NAME=$APP_NAME
ENV API_PREFIX=$API_PREFIX
ENV APP_FALLBACK_LANGUAGE=$APP_FALLBACK_LANGUAGE
ENV APP_HEADER_LANGUAGE=$APP_HEADER_LANGUAGE
ENV FRONTEND_DOMAIN=$FRONTEND_DOMAIN
ENV BACKEND_DOMAIN=$BACKEND_DOMAIN
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_NAME=$DATABASE_NAME
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV MINIO_ROOT_USER=$MINIO_ROOT_USER
ENV MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
ENV FILE_DRIVER=$FILE_DRIVER
ENV ACCESS_KEY_ID=$ACCESS_KEY_ID
ENV SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
ENV MAIL_HOST=$MAIL_HOST
ENV MAIL_PORT=$MAIL_PORT
ENV MAIL_USERNAME=$MAIL_USERNAME
ENV MAIL_PASSWORD=$MAIL_PASSWORD
ENV MAIL_IGNORE_TLS=$MAIL_IGNORE_TLS
ENV MAIL_SECURE=$MAIL_SECURE
ENV MAIL_REQUIRE_TLS=$MAIL_REQUIRE_TLS
ENV MAIL_DEFAULT_EMAIL=$MAIL_DEFAULT_EMAIL
ENV MAIL_DEFAULT_NAME=$MAIL_DEFAULT_NAME
ENV MAIL_CLIENT_PORT=$MAIL_CLIENT_PORT
ENV AUTH_JWT_SECRET=$AUTH_JWT_SECRET
ENV AUTH_JWT_TOKEN_EXPIRES_IN=$AUTH_JWT_TOKEN_EXPIRES_IN
ENV AUTH_REFRESH_SECRET=$AUTH_REFRESH_SECRET
ENV AUTH_REFRESH_TOKEN_EXPIRES_IN=$AUTH_REFRESH_TOKEN_EXPIRES_IN
ENV AUTH_FORGOT_SECRET=$AUTH_FORGOT_SECRET
ENV AUTH_FORGOT_TOKEN_EXPIRES_IN=$AUTH_FORGOT_TOKEN_EXPIRES_IN
ENV AUTH_CONFIRM_EMAIL_SECRET=$AUTH_CONFIRM_EMAIL_SECRET
ENV AUTH_CONFIRM_EMAIL_TOKEN_EXPIRES_IN=$AUTH_CONFIRM_EMAIL_TOKEN_EXPIRES_IN

RUN chmod +x /opt/startup.relational.dev.sh
RUN sed -i 's/\r//g' /opt/wait-for-it.sh
RUN sed -i 's/\r//g' /opt/startup.relational.dev.sh

WORKDIR /usr/src/app
RUN if [ ! -f .env ]; then cp env-example-relational .env; fi
RUN npm run build

CMD ["/opt/startup.relational.dev.sh"]
