services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' # HTTP
      - '81:81' # Admin panel
      - '443:443' # HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - public
  postgres:
    container_name: museum-db
    image: postgis/postgis:15-3.3-alpine
    restart: always
    networks:
      - public
      - internal
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - .env
    volumes:
      - museum-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    container_name: museum-cache
    image: redis:7-alpine
    restart: always
    networks:
      - internal

  minio:
    image: minio/minio:latest
    restart: always
    container_name: museum-storage
    networks:
      - internal
      - public
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":${MINIO_WEB_PORT}"
    ports:
      - ${MINIO_WEB_PORT}:${MINIO_WEB_PORT}
      - ${MINIO_PORT}:${MINIO_PORT}

  api:
    container_name: museum-api
    image: davys/museum-api:latest
    restart: always
    env_file:
      - .env
    networks:
      - internal
      - public

    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  museum-db:
    name: museum-db-volume
  minio_data:
    name: minio-storage-volume

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
