services:
  postgres:
    container_name: museum-db
    image: postgres:16.3-alpine
    networks:
      - internal
    volumes:
      - museum-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    container_name: maildev
    build:
      context: .
      dockerfile: maildev.Dockerfile
    networks:
      - internal

  redis:
    container_name: museum-cache
    image: redis:7-alpine
    networks:
      - internal

  minio:
    image: minio/minio:latest
    container_name: museum-storage
    networks:
      - internal
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data

  api:
    container_name: museum-api
    image: ghcr.io/dunseen/museum-api:latest
    restart: always
    env_file:
      - .env
    networks:
      - internal
      - public

    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  museum-db:
    name: museum-db-volume
  minio_data:
    name: minio-storage-volume

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
