services:
  postgres:
    container_name: museum-db
    image: postgres:16.3-alpine
    networks:
      - public
      - internal
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - .env
    volumes:
      - museum-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    container_name: museum-cache
    image: redis:7-alpine
    networks:
      - internal

  minio:
    image: minio/minio:latest
    container_name: museum-storage
    networks:
      - internal
      - public
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data
    ports:
      - ${MINIO_WEB_PORT}:${MINIO_WEB_PORT}

  api:
    container_name: museum-api
    image: ghcr.io/dunseen/museum-api:latest
    restart: always
    env_file:
      - .env
    networks:
      - internal
      - public

    ports:
      - ${APP_PORT}:${APP_PORT}
env_file:
  - .env
volumes:
  museum-db:
    name: museum-db-volume
  minio_data:
    name: minio-storage-volume

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
