services:
  postgres:
    container_name: museum-db
    image: postgres:16.3-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    container_name: maildev
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  redis:
    container_name: museum-cache
    image: redis:7-alpine
    ports:
      - 6379:6379

  minio:
    image: minio/minio:latest
    container_name: museum-storage
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - '9000:9000' # MinIO web interface
      - '9001:9001' # MinIO console (optional)
    volumes:
      - minio_data:/data
    command: server /data

  api:
    container_name: museum-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  boilerplate-db:
  minio_data:
